### ISSUE TITLE
getting this error

### ISSUE THREAD

**Issue by rbs250** [bmpasini/instabot#1]
Hi bmpasini, thank you for such an awesome code!

I did everything as instructed, and all went smooth, but I get this error when I try to run the last command: 

`MacBook-Pro-3:instabot-master USER$ python3 src/instabot.py
  File "src/instabot.py", line 19
    self.logger.log('InstaBot v0.1 will like ' + str(self.total_likes) + ' photos in total'))
                                                                                            ^
SyntaxError: invalid syntax
`

Can you tell me what I'm doing wrong? 
Thank you!!! 🙌🏻

**Comment by eshem** [comment]
@rbs250 change it to:
```self.logger.log('InstaBot v0.1 will like ' + str(self.total_likes) + ' photos in total')```

**Comment by rbs250** [comment]
@eshem hey man, thanks a lot!
I almost got it working...
Now I'm getting 

`MacBook-Pro-3:instabot-master USER$ python3 src/instabot.py
Traceback (most recent call last):
  File "src/instabot.py", line 1, in <module>
    import yaml, requests, random, time, datetime, json, sys
ImportError: No module named 'yaml'`

Have any suggestions?
Thanks again!

**Comment by bmpasini** [comment]
@rbs250 Glad you liked it! You have to install the dependencies, using `sudo pip install -r config/dependencies.txt`. If you don't have `pip` installed, try something like `brew install pip`. If you don't have homebrew installed, follow [these](http://brew.sh/) instructions.

**Comment by rbs250** [comment]
@bmpasini Hey Bruno, Thanks for the support!!
 I did all of it, however still getting this syntax error for some reason :/

`MacBook-Pro-3:InstaBot user$ python3 src/instabot.py
  File "src/instabot.py", line 19
    self.logger.log('InstaBot v0.1 will like ' + str(self.total_likes) + ' photos in total'))
                                                                                            ^
SyntaxError: invalid syntax`

All the dependencies are satisfied, pip is installed through homebrew.
And when trying the fix @eshem suggested, I'm getting

`MacBook-Pro-3:InstaBot user$ python3 src/instabot.py
Traceback (most recent call last):
  File "src/instabot.py", line 1, in <module>
    import yaml, requests, random, time, datetime, json, sys
ImportError: No module named 'yaml'`

Any ideas on how to solve this?
Thank you very much!!

**Comment by rbs250** [comment]
Hey @virginsince1997
Did that too already, I'm getting this now:

`MacBook-Pro-3:src user$ sudo pip install pyyaml
Password:
The directory '/Users/user/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/user/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied (use --upgrade to upgrade): pyyaml in /Library/Python/2.7/site-packages
`

Might be the cause of the issue?

**Comment by virginsince1997** [comment]
sudo -H pip install foo
sudo -H pip install pyyaml

**Comment by virginsince1997** [comment]
brew install libyaml sudo python -m easy_install pyyaml

Try Em

**Comment by rbs250** [comment]
@virginsince1997 Thanks, but still not luck :/

Getting this:
`MacBook-Pro-3:instabot-master user$ sudo -H pip install foo
Password:
Collecting foo
  Could not find a version that satisfies the requirement foo (from versions: )
No matching distribution found for foo
MacBook-Pro-3:instabot-master user$ sudo -H pip install pyyaml
Requirement already satisfied (use --upgrade to upgrade): pyyaml in /Library/Python/2.7/site-packages
MacBook-Pro-3:instabot-master user$ brew install libyaml sudo python -m easy_install pyyaml
Error: No available formula with the name "sudo" 
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
Error: No formulae found in taps.
`

Thanks for the assistance!! :)

**Comment by virginsince1997** [comment]
brew install libyaml sudo python -m easy_install pyyaml

If it doesn't work try upgrading pyyaml

**Comment by bmpasini** [comment]
@rbs250, please try this:

`sudo chmod -R 777 /Users/user/Library/Caches/pip`

Then try installing pyyaml again.

`sudo pip install pyyaml`

**Comment by bmpasini** [comment]
@rbs250, I just noticed that `pyyaml` has been installed already for you, but for Python version 2.7. This scripts only work with python 3+ versions. Try installing `pip3`:

**Comment by rbs250** [comment]
Yep, that was the issue. 😊
Thank you so much, all of you!!!🙌🏻
