### ISSUE TITLE
created a package from your code.

### ISSUE THREAD

**Issue by vinitkumar** [bmpasini/instabot#2]
Hi Bruno,

First of all, many thanks for writing and sharing instabot. It has been a great help for me to automate some liking jobs for my wife's instagram account.

Well, I created a package based on your code here https://github.com/vinitkumar/instabote/ . I am not planning to upload it to pypi. I just wanted to clean the code & add some more changes to the liking algorithms and maybe add more features in future. 

I have given proper credit and disclaimer in the [readme](https://github.com/vinitkumar/instabote#instabote) as well as [setup.py](https://github.com/vinitkumar/instabote/blob/master/setup.py#L9).

Let me know if you want any changes or if you have any suggestion.

Thanks!
Vinit

**Comment by bmpasini** [comment]
Hi Vinit,

It is great to know you found it useful. I also use it on my girlfriend's Instagram. Thank you for giving credit on your repo.

In terms of suggestions, I always think about coming back to this project and adding a feature for following people and after a few days unfollowing them. Just an idea, if you consider adding new features to it in the future.

Best,
Bruno

**Comment by vinitkumar** [comment]
@bmpasini I think I would be able to implement it using sqlite or something to store user and their timestamp and using that as configurable option to unfollow those people. Thanks for your kindness for letting me use your code. I will close this issue now.

Cheers! :)
